# Using Flask to serve a machine learning model as a RESTful webservice # 
## Reference: ##
https://www.youtube.com/watch?v=s-i6nzXQF3g

In [37]:
import numpy as np
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

import pickle
import requests, json

## Build a simple model

In [11]:
from sklearn.datasets import load_iris

iris = datasets.load_iris()

# data = load_iris()
# data.target[[10, 25, 50]]
# list(data.target_names)

print (iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [12]:
X = iris.data
y = iris.target

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [18]:
rfc = RandomForestClassifier(n_estimators = 160, n_jobs=2)

In [19]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=160, n_jobs=2,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [24]:
print ("Accuracy = {:.4f}".format(accuracy_score(y_test, rfc.predict(X_test))))

Accuracy = 0.9474


In [25]:
print (classification_report(y_test, rfc.predict(X_test)))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       0.93      0.93      0.93        14
          2       0.90      0.90      0.90        10

avg / total       0.95      0.95      0.95        38



## Model serialization

In [26]:
pickle.dump(rfc, open("iris_rfc.pkl", 'wb'))

In [27]:
my_random_forest = pickle.load(open('iris_rfc.pkl', 'rb'))

In [28]:
my_random_forest

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=160, n_jobs=2,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [50]:
print (classification_report(y_test, my_random_forest.predict(X_test)))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       0.93      0.93      0.93        14
          2       0.90      0.90      0.90        10

avg / total       0.95      0.95      0.95        38



In [52]:
print(X_test)

[[5.7 2.8 4.1 1.3]
 [5.3 3.7 1.5 0.2]
 [5.1 3.5 1.4 0.3]
 [6.4 3.1 5.5 1.8]
 [6.4 2.8 5.6 2.1]
 [6.  2.2 4.  1. ]
 [5.8 2.6 4.  1.2]
 [6.1 2.8 4.  1.3]
 [5.1 3.3 1.7 0.5]
 [6.1 2.9 4.7 1.4]
 [4.4 3.  1.3 0.2]
 [5.6 2.7 4.2 1.3]
 [5.6 2.8 4.9 2. ]
 [6.8 3.  5.5 2.1]
 [7.3 2.9 6.3 1.8]
 [4.7 3.2 1.3 0.2]
 [5.4 3.7 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [5.5 4.2 1.4 0.2]
 [5.7 4.4 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [5.8 2.7 3.9 1.2]
 [6.7 3.  5.  1.7]
 [6.5 2.8 4.6 1.5]
 [5.  2.3 3.3 1. ]
 [5.5 2.4 3.8 1.1]
 [4.8 3.1 1.6 0.2]
 [5.5 2.6 4.4 1.2]
 [6.  2.2 5.  1.5]
 [7.6 3.  6.6 2.1]
 [6.1 3.  4.9 1.8]
 [6.5 3.2 5.1 2. ]
 [5.  3.  1.6 0.2]
 [5.7 3.8 1.7 0.3]
 [6.2 2.9 4.3 1.3]
 [4.8 3.  1.4 0.1]
 [7.7 3.8 6.7 2.2]
 [4.4 3.2 1.3 0.2]]


In [57]:
print (type(X_test[0]))
print (type(X_test[0].reshape(1, -1)))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [55]:
X_test[0].reshape(1, -1)

array([[5.7, 2.8, 4.1, 1.3]])

In [54]:
my_random_forest.predict(X_test[0].reshape(1, -1))

array([1])

In [92]:
url = "http://localhost:9000/api"
data = json.dumps({'sl':5.84, 'sw':3.0, 'pl':3.79, 'pw':1.1})
print (data)
r = requests.post(url, data)
print (r.json())

{"sl": 5.84, "sw": 3.0, "pl": 3.79, "pw": 1.1}
{'results': [1]}


In [42]:
a = np.array([[1,2,3], [4,5,6]])
print (a.reshape(-1, 1))

print (a.reshape(1, -1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]
